<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="67540" started-at="2017-06-09T07:09:13Z" finished-at="2017-06-09T07:10:20Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="67540" started-at="2017-06-09T07:09:13Z" finished-at="2017-06-09T07:10:20Z">
      <class name="testcasePackage.Testcase1">
        <test-method status="FAIL" signature="tc1(java.lang.String, java.lang.String)[pri:0, instance:testcasePackage.Testcase1@f777e8]" name="tc1" duration-ms="36" started-at="2017-06-09T12:39:53Z" data-provider="getData" finished-at="2017-06-09T12:39:53Z">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
Data provider mismatch
Method: tc1([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String)computer]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: tc1([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String)computer]
	at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:49)
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1187)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc1 -->
      </class> <!-- testcasePackage.Testcase1 -->
      <class name="testcasePackage.Testcase2">
        <test-method status="FAIL" signature="tc2(java.lang.String)[pri:0, instance:testcasePackage.Testcase2@1ec2012]" name="tc2" duration-ms="20724" started-at="2017-06-09T12:39:33Z" data-provider="getData" finished-at="2017-06-09T12:39:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[computer]]>
              </value>
            </param>
          </params>
          <exception class="junit.framework.AssertionFailedError">
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.fail(Assert.java:64)
	at basePackage.Base.getElement(Base.java:134)
	at basePackage.Base.click(Base.java:193)
	at testcasePackage.Testcase2.tc2(Testcase2.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method status="PASS" signature="end1()[pri:0, instance:testcasePackage.Testcase2@1ec2012]" name="end1" is-config="true" duration-ms="1991" started-at="2017-06-09T12:40:17Z" finished-at="2017-06-09T12:40:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end1 -->
        <test-method status="PASS" signature="end1()[pri:0, instance:testcasePackage.Testcase3@2a079c]" name="end1" is-config="true" duration-ms="734" started-at="2017-06-09T12:40:19Z" finished-at="2017-06-09T12:40:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end1 -->
        <test-method status="PASS" signature="end1()[pri:0, instance:testcasePackage.Testcase4@1686d1f]" name="end1" is-config="true" duration-ms="748" started-at="2017-06-09T12:40:19Z" finished-at="2017-06-09T12:40:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- end1 -->
      </class> <!-- testcasePackage.Testcase2 -->
      <class name="testcasePackage.Testcase3">
        <test-method status="PASS" signature="tc3()[pri:0, instance:testcasePackage.Testcase3@2a079c]" name="tc3" duration-ms="19645" started-at="2017-06-09T12:39:13Z" finished-at="2017-06-09T12:39:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
      </class> <!-- testcasePackage.Testcase3 -->
      <class name="testcasePackage.Testcase4">
        <test-method status="PASS" signature="tc1()[pri:0, instance:testcasePackage.Testcase4@1686d1f]" name="tc1" duration-ms="23258" started-at="2017-06-09T12:39:53Z" finished-at="2017-06-09T12:40:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc1 -->
      </class> <!-- testcasePackage.Testcase4 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
